
package his;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SelfSrvTermbService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://9.28.8.2/bankhis/SelfSrvTermbService.asmx?wsdl")
public class SelfSrvTermbService
    extends Service
{

    private final static URL SELFSRVTERMBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SELFSRVTERMBSERVICE_EXCEPTION;
    private final static QName SELFSRVTERMBSERVICE_QNAME = new QName("http://tempuri.org/", "SelfSrvTermbService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://9.28.8.2/bankhis/SelfSrvTermbService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SELFSRVTERMBSERVICE_WSDL_LOCATION = url;
        SELFSRVTERMBSERVICE_EXCEPTION = e;
    }

    public SelfSrvTermbService() {
        super(__getWsdlLocation(), SELFSRVTERMBSERVICE_QNAME);
    }

    public SelfSrvTermbService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SELFSRVTERMBSERVICE_QNAME, features);
    }

    public SelfSrvTermbService(URL wsdlLocation) {
        super(wsdlLocation, SELFSRVTERMBSERVICE_QNAME);
    }

    public SelfSrvTermbService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SELFSRVTERMBSERVICE_QNAME, features);
    }

    public SelfSrvTermbService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SelfSrvTermbService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SelfSrvTermbServiceSoap
     */
    @WebEndpoint(name = "SelfSrvTermbServiceSoap")
    public SelfSrvTermbServiceSoap getSelfSrvTermbServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "SelfSrvTermbServiceSoap"), SelfSrvTermbServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SelfSrvTermbServiceSoap
     */
    @WebEndpoint(name = "SelfSrvTermbServiceSoap")
    public SelfSrvTermbServiceSoap getSelfSrvTermbServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SelfSrvTermbServiceSoap"), SelfSrvTermbServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SELFSRVTERMBSERVICE_EXCEPTION!= null) {
            throw SELFSRVTERMBSERVICE_EXCEPTION;
        }
        return SELFSRVTERMBSERVICE_WSDL_LOCATION;
    }

}
