
package his;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SelfSrvTermbServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SelfSrvTermbServiceSoap {


    /**
     * 
     * @param inXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NetTest", action = "http://tempuri.org/NetTest")
    @WebResult(name = "NetTestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NetTest", targetNamespace = "http://tempuri.org/", className = "his.NetTest")
    @ResponseWrapper(localName = "NetTestResponse", targetNamespace = "http://tempuri.org/", className = "his.NetTestResponse")
    public String netTest(
        @WebParam(name = "inXml", targetNamespace = "http://tempuri.org/")
        String inXml);

    /**
     * 
     * @param inXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetFeeitemDetail", action = "http://tempuri.org/GdaGetFeeitemDetail")
    @WebResult(name = "GdaGetFeeitemDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetFeeitemDetail", targetNamespace = "http://tempuri.org/", className = "his.GdaGetFeeitemDetail")
    @ResponseWrapper(localName = "GdaGetFeeitemDetailResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetFeeitemDetailResponse")
    public String gdaGetFeeitemDetail(
        @WebParam(name = "inXml", targetNamespace = "http://tempuri.org/")
        String inXml);

    /**
     * 
     * @param inXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRegistList", action = "http://tempuri.org/GetRegistList")
    @WebResult(name = "GetRegistListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRegistList", targetNamespace = "http://tempuri.org/", className = "his.GetRegistList")
    @ResponseWrapper(localName = "GetRegistListResponse", targetNamespace = "http://tempuri.org/", className = "his.GetRegistListResponse")
    public String getRegistList(
        @WebParam(name = "inXml", targetNamespace = "http://tempuri.org/")
        String inXml);

    /**
     * 
     * @param inXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBillInfo", action = "http://tempuri.org/GetBillInfo")
    @WebResult(name = "GetBillInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBillInfo", targetNamespace = "http://tempuri.org/", className = "his.GetBillInfo")
    @ResponseWrapper(localName = "GetBillInfoResponse", targetNamespace = "http://tempuri.org/", className = "his.GetBillInfoResponse")
    public String getBillInfo(
        @WebParam(name = "inXml", targetNamespace = "http://tempuri.org/")
        String inXml);

    /**
     * 
     * @param inXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AutoOPBillCharge", action = "http://tempuri.org/AutoOPBillCharge")
    @WebResult(name = "AutoOPBillChargeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AutoOPBillCharge", targetNamespace = "http://tempuri.org/", className = "his.AutoOPBillCharge")
    @ResponseWrapper(localName = "AutoOPBillChargeResponse", targetNamespace = "http://tempuri.org/", className = "his.AutoOPBillChargeResponse")
    public String autoOPBillCharge(
        @WebParam(name = "inXml", targetNamespace = "http://tempuri.org/")
        String inXml);

    /**
     * 
     * @param strval
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/newcard")
    @WebResult(name = "newcardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "newcard", targetNamespace = "http://tempuri.org/", className = "his.Newcard")
    @ResponseWrapper(localName = "newcardResponse", targetNamespace = "http://tempuri.org/", className = "his.NewcardResponse")
    public String newcard(
        @WebParam(name = "strval", targetNamespace = "http://tempuri.org/")
        String strval);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/test")
    @WebResult(name = "testResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "test", targetNamespace = "http://tempuri.org/", className = "his.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://tempuri.org/", className = "his.TestResponse")
    public String test();

    /**
     * 
     * @param strval
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/checknewcard")
    @WebResult(name = "checknewcardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "checknewcard", targetNamespace = "http://tempuri.org/", className = "his.Checknewcard")
    @ResponseWrapper(localName = "checknewcardResponse", targetNamespace = "http://tempuri.org/", className = "his.ChecknewcardResponse")
    public String checknewcard(
        @WebParam(name = "strval", targetNamespace = "http://tempuri.org/")
        String strval);

    /**
     * 
     * @param strval
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/cardloss")
    @WebResult(name = "cardlossResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "cardloss", targetNamespace = "http://tempuri.org/", className = "his.Cardloss")
    @ResponseWrapper(localName = "cardlossResponse", targetNamespace = "http://tempuri.org/", className = "his.CardlossResponse")
    public String cardloss(
        @WebParam(name = "strval", targetNamespace = "http://tempuri.org/")
        String strval);

    /**
     * 
     * @param strval
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/checkcard")
    @WebResult(name = "checkcardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "checkcard", targetNamespace = "http://tempuri.org/", className = "his.Checkcard")
    @ResponseWrapper(localName = "checkcardResponse", targetNamespace = "http://tempuri.org/", className = "his.CheckcardResponse")
    public String checkcard(
        @WebParam(name = "strval", targetNamespace = "http://tempuri.org/")
        String strval);

    /**
     * 
     * @param strval
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getcardinfo")
    @WebResult(name = "getcardinfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getcardinfo", targetNamespace = "http://tempuri.org/", className = "his.Getcardinfo")
    @ResponseWrapper(localName = "getcardinfoResponse", targetNamespace = "http://tempuri.org/", className = "his.GetcardinfoResponse")
    public String getcardinfo(
        @WebParam(name = "strval", targetNamespace = "http://tempuri.org/")
        String strval);

    /**
     * 
     * @param strval
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/mpassword")
    @WebResult(name = "mpasswordResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mpassword", targetNamespace = "http://tempuri.org/", className = "his.Mpassword")
    @ResponseWrapper(localName = "mpasswordResponse", targetNamespace = "http://tempuri.org/", className = "his.MpasswordResponse")
    public String mpassword(
        @WebParam(name = "strval", targetNamespace = "http://tempuri.org/")
        String strval);

    /**
     * 
     * @param strval
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getdoctor")
    @WebResult(name = "getdoctorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getdoctor", targetNamespace = "http://tempuri.org/", className = "his.Getdoctor")
    @ResponseWrapper(localName = "getdoctorResponse", targetNamespace = "http://tempuri.org/", className = "his.GetdoctorResponse")
    public String getdoctor(
        @WebParam(name = "strval", targetNamespace = "http://tempuri.org/")
        String strval);

    /**
     * 
     * @param strval
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getmzks")
    @WebResult(name = "getmzksResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getmzks", targetNamespace = "http://tempuri.org/", className = "his.Getmzks")
    @ResponseWrapper(localName = "getmzksResponse", targetNamespace = "http://tempuri.org/", className = "his.GetmzksResponse")
    public String getmzks(
        @WebParam(name = "strval", targetNamespace = "http://tempuri.org/")
        String strval);

    /**
     * 
     * @param strval
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getregmoeny")
    @WebResult(name = "getregmoenyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getregmoeny", targetNamespace = "http://tempuri.org/", className = "his.Getregmoeny")
    @ResponseWrapper(localName = "getregmoenyResponse", targetNamespace = "http://tempuri.org/", className = "his.GetregmoenyResponse")
    public String getregmoeny(
        @WebParam(name = "strval", targetNamespace = "http://tempuri.org/")
        String strval);

    /**
     * 
     * @param strval
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getcardcount")
    @WebResult(name = "getcardcountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getcardcount", targetNamespace = "http://tempuri.org/", className = "his.Getcardcount")
    @ResponseWrapper(localName = "getcardcountResponse", targetNamespace = "http://tempuri.org/", className = "his.GetcardcountResponse")
    public String getcardcount(
        @WebParam(name = "strval", targetNamespace = "http://tempuri.org/")
        String strval);

    /**
     * 
     * @param strval
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/regbydoct")
    @WebResult(name = "regbydoctResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "regbydoct", targetNamespace = "http://tempuri.org/", className = "his.Regbydoct")
    @ResponseWrapper(localName = "regbydoctResponse", targetNamespace = "http://tempuri.org/", className = "his.RegbydoctResponse")
    public String regbydoct(
        @WebParam(name = "strval", targetNamespace = "http://tempuri.org/")
        String strval);

    /**
     * 
     * @param strval
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/checkidencard")
    @WebResult(name = "checkidencardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "checkidencard", targetNamespace = "http://tempuri.org/", className = "his.Checkidencard")
    @ResponseWrapper(localName = "checkidencardResponse", targetNamespace = "http://tempuri.org/", className = "his.CheckidencardResponse")
    public String checkidencard(
        @WebParam(name = "strval", targetNamespace = "http://tempuri.org/")
        String strval);

    /**
     * 
     * @param strval
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/setbankcard")
    @WebResult(name = "setbankcardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "setbankcard", targetNamespace = "http://tempuri.org/", className = "his.Setbankcard")
    @ResponseWrapper(localName = "setbankcardResponse", targetNamespace = "http://tempuri.org/", className = "his.SetbankcardResponse")
    public String setbankcard(
        @WebParam(name = "strval", targetNamespace = "http://tempuri.org/")
        String strval);

    /**
     * 
     * @param inXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPatChargeType", action = "http://tempuri.org/GetPatChargeType")
    @WebResult(name = "GetPatChargeTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPatChargeType", targetNamespace = "http://tempuri.org/", className = "his.GetPatChargeType")
    @ResponseWrapper(localName = "GetPatChargeTypeResponse", targetNamespace = "http://tempuri.org/", className = "his.GetPatChargeTypeResponse")
    public String getPatChargeType(
        @WebParam(name = "inXml", targetNamespace = "http://tempuri.org/")
        String inXml);

    /**
     * 
     * @param inXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetOutPay", action = "http://tempuri.org/GdaGetOutPay")
    @WebResult(name = "GdaGetOutPayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetOutPay", targetNamespace = "http://tempuri.org/", className = "his.GdaGetOutPay")
    @ResponseWrapper(localName = "GdaGetOutPayResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetOutPayResponse")
    public String gdaGetOutPay(
        @WebParam(name = "inXml", targetNamespace = "http://tempuri.org/")
        String inXml);

    /**
     * 
     * @param inXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetOutPayDetail", action = "http://tempuri.org/GdaGetOutPayDetail")
    @WebResult(name = "GdaGetOutPayDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetOutPayDetail", targetNamespace = "http://tempuri.org/", className = "his.GdaGetOutPayDetail")
    @ResponseWrapper(localName = "GdaGetOutPayDetailResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetOutPayDetailResponse")
    public String gdaGetOutPayDetail(
        @WebParam(name = "inXml", targetNamespace = "http://tempuri.org/")
        String inXml);

    /**
     * 
     * @param inXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaInsertOutPay", action = "http://tempuri.org/GdaInsertOutPay")
    @WebResult(name = "GdaInsertOutPayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaInsertOutPay", targetNamespace = "http://tempuri.org/", className = "his.GdaInsertOutPay")
    @ResponseWrapper(localName = "GdaInsertOutPayResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaInsertOutPayResponse")
    public String gdaInsertOutPay(
        @WebParam(name = "inXml", targetNamespace = "http://tempuri.org/")
        String inXml);

    /**
     * 
     * @param inXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPatSIState", action = "http://tempuri.org/GetPatSIState")
    @WebResult(name = "GetPatSIStateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPatSIState", targetNamespace = "http://tempuri.org/", className = "his.GetPatSIState")
    @ResponseWrapper(localName = "GetPatSIStateResponse", targetNamespace = "http://tempuri.org/", className = "his.GetPatSIStateResponse")
    public String getPatSIState(
        @WebParam(name = "inXml", targetNamespace = "http://tempuri.org/")
        String inXml);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "YTDocSchedules", action = "http://tempuri.org/YTDocSchedules")
    @WebResult(name = "YTDocSchedulesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "YTDocSchedules", targetNamespace = "http://tempuri.org/", className = "his.YTDocSchedules")
    @ResponseWrapper(localName = "YTDocSchedulesResponse", targetNamespace = "http://tempuri.org/", className = "his.YTDocSchedulesResponse")
    public String ytDocSchedules(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "YTConfirmBook", action = "http://tempuri.org/YTConfirmBook")
    @WebResult(name = "YTConfirmBookResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "YTConfirmBook", targetNamespace = "http://tempuri.org/", className = "his.YTConfirmBook")
    @ResponseWrapper(localName = "YTConfirmBookResponse", targetNamespace = "http://tempuri.org/", className = "his.YTConfirmBookResponse")
    public String ytConfirmBook(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "YTGetBookList", action = "http://tempuri.org/YTGetBookList")
    @WebResult(name = "YTGetBookListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "YTGetBookList", targetNamespace = "http://tempuri.org/", className = "his.YTGetBookList")
    @ResponseWrapper(localName = "YTGetBookListResponse", targetNamespace = "http://tempuri.org/", className = "his.YTGetBookListResponse")
    public String ytGetBookList(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "YTTakeBook", action = "http://tempuri.org/YTTakeBook")
    @WebResult(name = "YTTakeBookResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "YTTakeBook", targetNamespace = "http://tempuri.org/", className = "his.YTTakeBook")
    @ResponseWrapper(localName = "YTTakeBookResponse", targetNamespace = "http://tempuri.org/", className = "his.YTTakeBookResponse")
    public String ytTakeBook(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "YTCancelBook", action = "http://tempuri.org/YTCancelBook")
    @WebResult(name = "YTCancelBookResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "YTCancelBook", targetNamespace = "http://tempuri.org/", className = "his.YTCancelBook")
    @ResponseWrapper(localName = "YTCancelBookResponse", targetNamespace = "http://tempuri.org/", className = "his.YTCancelBookResponse")
    public String ytCancelBook(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "YTBookingDeptDoctor", action = "http://tempuri.org/YTBookingDeptDoctor")
    @WebResult(name = "YTBookingDeptDoctorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "YTBookingDeptDoctor", targetNamespace = "http://tempuri.org/", className = "his.YTBookingDeptDoctor")
    @ResponseWrapper(localName = "YTBookingDeptDoctorResponse", targetNamespace = "http://tempuri.org/", className = "his.YTBookingDeptDoctorResponse")
    public String ytBookingDeptDoctor(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetStaff", action = "http://tempuri.org/GdaGetStaff")
    @WebResult(name = "GdaGetStaffResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetStaff", targetNamespace = "http://tempuri.org/", className = "his.GdaGetStaff")
    @ResponseWrapper(localName = "GdaGetStaffResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetStaffResponse")
    public String gdaGetStaff(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetDept", action = "http://tempuri.org/GdaGetDept")
    @WebResult(name = "GdaGetDeptResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetDept", targetNamespace = "http://tempuri.org/", className = "his.GdaGetDept")
    @ResponseWrapper(localName = "GdaGetDeptResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetDeptResponse")
    public String gdaGetDept(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetStaffDept", action = "http://tempuri.org/GdaGetStaffDept")
    @WebResult(name = "GdaGetStaffDeptResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetStaffDept", targetNamespace = "http://tempuri.org/", className = "his.GdaGetStaffDept")
    @ResponseWrapper(localName = "GdaGetStaffDeptResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetStaffDeptResponse")
    public String gdaGetStaffDept(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetFeeitem", action = "http://tempuri.org/GdaGetFeeitem")
    @WebResult(name = "GdaGetFeeitemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetFeeitem", targetNamespace = "http://tempuri.org/", className = "his.GdaGetFeeitem")
    @ResponseWrapper(localName = "GdaGetFeeitemResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetFeeitemResponse")
    public String gdaGetFeeitem(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaDocSchedules", action = "http://tempuri.org/GdaDocSchedules")
    @WebResult(name = "GdaDocSchedulesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaDocSchedules", targetNamespace = "http://tempuri.org/", className = "his.GdaDocSchedules")
    @ResponseWrapper(localName = "GdaDocSchedulesResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaDocSchedulesResponse")
    public String gdaDocSchedules(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetOutPatDoc", action = "http://tempuri.org/GdaGetOutPatDoc")
    @WebResult(name = "GdaGetOutPatDocResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetOutPatDoc", targetNamespace = "http://tempuri.org/", className = "his.GdaGetOutPatDoc")
    @ResponseWrapper(localName = "GdaGetOutPatDocResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetOutPatDocResponse")
    public String gdaGetOutPatDoc(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetInPatDoc", action = "http://tempuri.org/GdaGetInPatDoc")
    @WebResult(name = "GdaGetInPatDocResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetInPatDoc", targetNamespace = "http://tempuri.org/", className = "his.GdaGetInPatDoc")
    @ResponseWrapper(localName = "GdaGetInPatDocResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetInPatDocResponse")
    public String gdaGetInPatDoc(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetHosChargeTotal", action = "http://tempuri.org/GdaGetHosChargeTotal")
    @WebResult(name = "GdaGetHosChargeTotalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetHosChargeTotal", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosChargeTotal")
    @ResponseWrapper(localName = "GdaGetHosChargeTotalResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosChargeTotalResponse")
    public String gdaGetHosChargeTotal(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetHosPayDetail", action = "http://tempuri.org/GdaGetHosPayDetail")
    @WebResult(name = "GdaGetHosPayDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetHosPayDetail", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosPayDetail")
    @ResponseWrapper(localName = "GdaGetHosPayDetailResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosPayDetailResponse")
    public String gdaGetHosPayDetail(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetHosizedRecord", action = "http://tempuri.org/GdaGetHosizedRecord")
    @WebResult(name = "GdaGetHosizedRecordResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetHosizedRecord", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosizedRecord")
    @ResponseWrapper(localName = "GdaGetHosizedRecordResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosizedRecordResponse")
    public String gdaGetHosizedRecord(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetHosizedCharge", action = "http://tempuri.org/GdaGetHosizedCharge")
    @WebResult(name = "GdaGetHosizedChargeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetHosizedCharge", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosizedCharge")
    @ResponseWrapper(localName = "GdaGetHosizedChargeResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosizedChargeResponse")
    public String gdaGetHosizedCharge(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetHosizedChargeDetail", action = "http://tempuri.org/GdaGetHosizedChargeDetail")
    @WebResult(name = "GdaGetHosizedChargeDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetHosizedChargeDetail", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosizedChargeDetail")
    @ResponseWrapper(localName = "GdaGetHosizedChargeDetailResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosizedChargeDetailResponse")
    public String gdaGetHosizedChargeDetail(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetHosizedChargeRecord", action = "http://tempuri.org/GdaGetHosizedChargeRecord")
    @WebResult(name = "GdaGetHosizedChargeRecordResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetHosizedChargeRecord", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosizedChargeRecord")
    @ResponseWrapper(localName = "GdaGetHosizedChargeRecordResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosizedChargeRecordResponse")
    public String gdaGetHosizedChargeRecord(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetHosizedReceipt", action = "http://tempuri.org/GdaGetHosizedReceipt")
    @WebResult(name = "GdaGetHosizedReceiptResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetHosizedReceipt", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosizedReceipt")
    @ResponseWrapper(localName = "GdaGetHosizedReceiptResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosizedReceiptResponse")
    public String gdaGetHosizedReceipt(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetHosizedReceiptDetail", action = "http://tempuri.org/GdaGetHosizedReceiptDetail")
    @WebResult(name = "GdaGetHosizedReceiptDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetHosizedReceiptDetail", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosizedReceiptDetail")
    @ResponseWrapper(localName = "GdaGetHosizedReceiptDetailResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosizedReceiptDetailResponse")
    public String gdaGetHosizedReceiptDetail(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GdaGetHosizedOneDay", action = "http://tempuri.org/GdaGetHosizedOneDay")
    @WebResult(name = "GdaGetHosizedOneDayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GdaGetHosizedOneDay", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosizedOneDay")
    @ResponseWrapper(localName = "GdaGetHosizedOneDayResponse", targetNamespace = "http://tempuri.org/", className = "his.GdaGetHosizedOneDayResponse")
    public String gdaGetHosizedOneDay(
        @WebParam(name = "inputInfo", targetNamespace = "http://tempuri.org/")
        String inputInfo);

}
