
package wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "mywsService", targetNamespace = "ws/getAge", wsdlLocation = "http://127.0.0.1:8080/myWS/services/mywsService?wsdl")
public class MywsService
    extends Service
{

    private final static URL MYWSSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/myWS/services/mywsService?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        MYWSSERVICE_WSDL_LOCATION = url;
    }

    public MywsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MywsService() {
        super(MYWSSERVICE_WSDL_LOCATION, new QName("ws/getAge", "mywsService"));
    }

    /**
     * 
     * @return
     *     returns MywsServicePortType
     */
    @WebEndpoint(name = "mywsServiceHttpPort")
    public MywsServicePortType getMywsServiceHttpPort() {
        return (MywsServicePortType)super.getPort(new QName("ws/getAge", "mywsServiceHttpPort"), MywsServicePortType.class);
    }

}
