
package wsimport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "mywsServicePortType", targetNamespace = "ws/getAge")
public interface MywsServicePortType {


    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "ws/getAge")
    @RequestWrapper(localName = "getAge", targetNamespace = "ws/getAge", className = "wsimport.GetAge")
    @ResponseWrapper(localName = "getAgeResponse", targetNamespace = "ws/getAge", className = "wsimport.GetAgeResponse")
    public String getAge(
        @WebParam(name = "in0", targetNamespace = "ws/getAge")
        int in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "ws/getAge")
    @RequestWrapper(localName = "getName", targetNamespace = "ws/getAge", className = "wsimport.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "ws/getAge", className = "wsimport.GetNameResponse")
    public String getName(
        @WebParam(name = "in0", targetNamespace = "ws/getAge")
        String in0);

}
