package com.sun309.webservice.sms;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Service", targetNamespace = "http://mas/")
public interface Service {

	/**
	 * 
	 * @param message
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "send", targetNamespace = "http://mas/", className = "com.sun309.webservice.sms.Send")
	@ResponseWrapper(localName = "sendResponse", targetNamespace = "http://mas/", className = "com.sun309.webservice.sms.SendResponse")
	public int send(
			@WebParam(name = "message", targetNamespace = "") Message message);

	/**
	 * 
	 * @param amount
	 * @param smID
	 * @return returns java.util.List<com.sun309.webservice.sms.RptItem>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "receiveRPT", targetNamespace = "http://mas/", className = "com.sun309.webservice.sms.ReceiveRPT")
	@ResponseWrapper(localName = "receiveRPTResponse", targetNamespace = "http://mas/", className = "com.sun309.webservice.sms.ReceiveRPTResponse")
	public List<RptItem> receiveRPT(
			@WebParam(name = "smID", targetNamespace = "") long smID,
			@WebParam(name = "amount", targetNamespace = "") int amount);

}
