package com.sun309.webservice.sms;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ServiceService service = new ServiceService();
 * Service portType = service.getServicePort();
 * portType.send(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ServiceService", targetNamespace = "http://mas/", wsdlLocation = "http://esb.expresspay.cn/mas/service/sun309?wsdl")
public class ServiceService extends javax.xml.ws.Service {

	private final static URL SERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.sun309.webservice.sms.ServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.sun309.webservice.sms.ServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://esb.expresspay.cn/mas/service/sun309?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://esb.expresspay.cn/mas/service/sun309?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SERVICESERVICE_WSDL_LOCATION = url;
	}

	public ServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ServiceService() {
		super(SERVICESERVICE_WSDL_LOCATION, new QName("http://mas/",
				"ServiceService"));
	}

	/**
	 * 
	 * @return returns Service
	 */
	@WebEndpoint(name = "ServicePort")
	public com.sun309.webservice.sms.Service getServicePort() {
		return super.getPort(new QName("http://mas/", "ServicePort"),
				Service.class);
	}
	
	public static void main(String args []){
		ServiceService service = new ServiceService();
		Message message = new Message();
		message.setContent("message2 ");
		message.setSmID(102115);
		List<String> mobiles = message.getMobile();
		mobiles.add("18933913689");
		int result = service.getServicePort().send(message);
		System.out.println("the result is :"+result);
	}

}
